### ISSUE TITLE
rasp pi

### ISSUE THREAD

**Issue by gedw99** [ycoroneos/G.E.R.T#4]
did you see the other golang project which runs on bare metal rasp PI ?

https://gokrazy.org/

---

Wondering what sort of response you got from the golang team about integrating changes into the go tree. Running on baremetal is very useful these days.

**Comment by ycoroneos** [comment]
That project is not a bare metal Go implementation, it's a user space written in Go. It's supposed to run on top of Linux whereas GERT is meant to completely replace it.

I never attempted to integrate GERT into mainline Go because it really seemed like a lot of work which wasn't relevant to my thesis. I think a good way to start though would be to define a new GOOS so that way the bare-metal hacks I put in can be toggled.

**Comment by gedw99** [comment]
@ycoroneos thank you for the thorough response.

Make me now think about using the docker on ARM project to achieve my objectives on running golang stuff on ARM embedded boards. Its more doable now you see.
The GUI i will run in a Webview and do IT between the two.
